<?php

return [
    'icons' => [
        [
            'key' => 'pf_gaji',
            'label' => 'Gaji',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_gaji.png',
        ],
        [
            'key' => 'pf_penjualan',
            'label' => 'Penjualan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_penjualan.png',
        ],
        [
            'key' => 'pf_bagi_hasil',
            'label' => 'Bagi Hasil',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_bagi_hasil.png',
        ],
        [
            'key' => 'pf_investasi',
            'label' => 'Investasi',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_investasi.png',
        ],
        [
            'key' => 'pf_top_up',
            'label' => 'Top Up',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_top_up.png',
        ],
        [
            'key' => 'pf_pemasukan_lainnya',
            'label' => 'Pemasukan Lainnya',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_pemasukan_lainnya.png',
        ],
        [
            'key' => 'pf_kebutuhan_pekerjaan',
            'label' => 'Kebutuhan Pekerjaan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_kebutuhan_pekerjaan.png',
        ],
        [
            'key' => 'pf_kebutuhan_pokok',
            'label' => 'Kebutuhan Pokok',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_kebutuhan_pokok.png',
        ],
        [
            'key' => 'pf_kesehatan',
            'label' => 'Kesehatan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_kesehatan.png',
        ],
        [
            'key' => 'pf_transportasi',
            'label' => 'Transportasi',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_transportasi.png',
        ],
        [
            'key' => 'pf_cicilan',
            'label' => 'Cicilan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_cicilan.png',
        ],
        [
            'key' => 'pf_hiburan',
            'label' => 'Hiburan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_hiburan.png',
        ],
        [
            'key' => 'pf_tagihan',
            'label' => 'Tagihan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_tagihan.png',
        ],
        [
            'key' => 'pf_tabungan',
            'label' => 'Tabungan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_tabungan.png',
        ],
        [
            'key' => 'pf_donasi',
            'label' => 'Donasi',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_donasi.png',
        ],
        [
            'key' => 'pf_pendidikan',
            'label' => 'Pendidikan',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_pendidikan.png',
        ],
        [
            'key' => 'pf_belanja',
            'label' => 'Belanja',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_belanja.png',
        ],
        [
            'key' => 'pf_pengeluaran_lainnya',
            'label' => 'Pengeluaran Lainnya',
            'tenant_group' => 'personal_family',
            'tenant_group_label' => 'Personal & Family',
            'asset_path' => 'images/category-icon-masks/pf_pengeluaran_lainnya.png',
        ],
        [
            'key' => 'tc_top_up_dana_operasional',
            'label' => 'Top Up Dana Operasional',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_top_up_dana_operasional.png',
        ],
        [
            'key' => 'tc_reimbursement_kantor',
            'label' => 'Reimbursement Kantor',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_reimbursement_kantor.png',
        ],
        [
            'key' => 'tc_refund_vendor',
            'label' => 'Refund Vendor',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_refund_vendor.png',
        ],
        [
            'key' => 'tc_pemasukan_lainnya',
            'label' => 'Pemasukan Lainnya',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_pemasukan_lainnya.png',
        ],
        [
            'key' => 'tc_transportasi_perjalanan',
            'label' => 'Transportasi & Perjalanan',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_transportasi_perjalanan.png',
        ],
        [
            'key' => 'tc_konsumsi',
            'label' => 'Konsumsi',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_konsumsi.png',
        ],
        [
            'key' => 'tc_atk_keperluan_kantor',
            'label' => 'ATK & Keperluan Kantor',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_atk_keperluan_kantor.png',
        ],
        [
            'key' => 'tc_komunikasi',
            'label' => 'Komunikasi',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_komunikasi.png',
        ],
        [
            'key' => 'tc_kurir_pengiriman',
            'label' => 'Kurir / Pengiriman',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_kurir_pengiriman.png',
        ],
        [
            'key' => 'tc_entertainment',
            'label' => 'Entertainment',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_entertainment.png',
        ],
        [
            'key' => 'tc_promosi_aktivasi_penjualan',
            'label' => 'Promosi & Aktivasi Penjualan',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_promosi_aktivasi_penjualan.png',
        ],
        [
            'key' => 'tc_biaya_meeting_klien',
            'label' => 'Biaya Meeting Klien',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_biaya_meeting_klien.png',
        ],
        [
            'key' => 'tc_kunjungan_lapangan',
            'label' => 'Kunjungan Lapangan',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_kunjungan_lapangan.png',
        ],
        [
            'key' => 'tc_recruitment',
            'label' => 'Recruitment',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_recruitment.png',
        ],
        [
            'key' => 'tc_employee_welfare',
            'label' => 'Employee Welfare',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_employee_welfare.png',
        ],
        [
            'key' => 'tc_housekeeping_pantry',
            'label' => 'Housekeeping & Pantry',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_housekeeping_pantry.png',
        ],
        [
            'key' => 'tc_perbaikan_pemeliharaan',
            'label' => 'Perbaikan & Pemeliharaan',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_perbaikan_pemeliharaan.png',
        ],
        [
            'key' => 'tc_operasional_kantor_lainnya',
            'label' => 'Operasional Kantor Lainnya',
            'tenant_group' => 'team_company',
            'tenant_group_label' => 'Teams & Company',
            'asset_path' => 'images/category-icon-masks/tc_operasional_kantor_lainnya.png',
        ],
        [
            'key' => 'umkm_penjualan',
            'label' => 'Penjualan',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_penjualan.png',
        ],
        [
            'key' => 'umkm_komisi_bagi_hasil',
            'label' => 'Komisi & Bagi Hasil',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_komisi_bagi_hasil.png',
        ],
        [
            'key' => 'umkm_return_investasi',
            'label' => 'Return Investasi',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_return_investasi.png',
        ],
        [
            'key' => 'umkm_bunga_tabungan',
            'label' => 'Bunga Tabungan',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_bunga_tabungan.png',
        ],
        [
            'key' => 'umkm_pendapatan_lainnya',
            'label' => 'Pendapatan Lainnya',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_pendapatan_lainnya.png',
        ],
        [
            'key' => 'umkm_bahan_baku',
            'label' => 'Bahan Baku',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_bahan_baku.png',
        ],
        [
            'key' => 'umkm_ongkos_kirim',
            'label' => 'Ongkos Kirim',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_ongkos_kirim.png',
        ],
        [
            'key' => 'umkm_operasional_produksi',
            'label' => 'Operasional Produksi',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_operasional_produksi.png',
        ],
        [
            'key' => 'umkm_operasional_kantor',
            'label' => 'Operasional Kantor',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_operasional_kantor.png',
        ],
        [
            'key' => 'umkm_gaji',
            'label' => 'Gaji',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_gaji.png',
        ],
        [
            'key' => 'umkm_bonus',
            'label' => 'Bonus',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_bonus.png',
        ],
        [
            'key' => 'umkm_iklan',
            'label' => 'Iklan',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_iklan.png',
        ],
        [
            'key' => 'umkm_endorsement',
            'label' => 'Endorsement',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_endorsement.png',
        ],
        [
            'key' => 'umkm_komisi_afiliasi',
            'label' => 'Komisi Afiliasi',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_komisi_afiliasi.png',
        ],
        [
            'key' => 'umkm_transportasi',
            'label' => 'Transportasi',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_transportasi.png',
        ],
        [
            'key' => 'umkm_sewa',
            'label' => 'Sewa',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_sewa.png',
        ],
        [
            'key' => 'umkm_administrasi',
            'label' => 'Administrasi',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_administrasi.png',
        ],
        [
            'key' => 'umkm_pajak',
            'label' => 'Pajak',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_pajak.png',
        ],
        [
            'key' => 'umkm_pengeluaran_lainnya',
            'label' => 'Pengeluaran Lainnya',
            'tenant_group' => 'umkm',
            'tenant_group_label' => 'UMKM',
            'asset_path' => 'images/category-icon-masks/umkm_pengeluaran_lainnya.png',
        ],
    ],
    'colors' => [
        [
            'key' => 'pf_gaji',
            'label' => 'Gaji',
            'bg_color' => '#e8f7e8',
            'icon_color' => '#24802e',
        ],
        [
            'key' => 'pf_penjualan',
            'label' => 'Penjualan',
            'bg_color' => '#fce3ed',
            'icon_color' => '#a61252',
        ],
        [
            'key' => 'pf_bagi_hasil',
            'label' => 'Bagi Hasil',
            'bg_color' => '#fffade',
            'icon_color' => '#eb800d',
        ],
        [
            'key' => 'pf_investasi',
            'label' => 'Investasi',
            'bg_color' => '#f0fae3',
            'icon_color' => '#89b56b',
        ],
        [
            'key' => 'pf_top_up',
            'label' => 'Top Up',
            'bg_color' => '#e0f2ff',
            'icon_color' => '#0d47a1',
        ],
        [
            'key' => 'pf_pemasukan_lainnya',
            'label' => 'Pemasukan Lainnya',
            'bg_color' => '#def7fc',
            'icon_color' => '#008594',
        ],
        [
            'key' => 'pf_kebutuhan_pekerjaan',
            'label' => 'Kebutuhan Pekerjaan',
            'bg_color' => '#ede6f7',
            'icon_color' => '#45269e',
        ],
        [
            'key' => 'pf_kebutuhan_pokok',
            'label' => 'Kebutuhan Pokok',
            'bg_color' => '#def5f2',
            'icon_color' => '#00695c',
        ],
        [
            'key' => 'pf_kesehatan',
            'label' => 'Kesehatan',
            'bg_color' => '#ffebeb',
            'icon_color' => '#dc6f6f',
        ],
        [
            'key' => 'pf_transportasi',
            'label' => 'Transportasi',
            'bg_color' => '#e0f2ff',
            'icon_color' => '#1466bf',
        ],
        [
            'key' => 'pf_cicilan',
            'label' => 'Cicilan',
            'bg_color' => '#fff2e0',
            'icon_color' => '#ef9f70',
        ],
        [
            'key' => 'pf_hiburan',
            'label' => 'Hiburan',
            'bg_color' => '#ede6f7',
            'icon_color' => '#6b1c99',
        ],
        [
            'key' => 'pf_tagihan',
            'label' => 'Tagihan',
            'bg_color' => '#fff7de',
            'icon_color' => '#f8b16f',
        ],
        [
            'key' => 'pf_tabungan',
            'label' => 'Tabungan',
            'bg_color' => '#e8f7e8',
            'icon_color' => '#2e8f38',
        ],
        [
            'key' => 'pf_donasi',
            'label' => 'Donasi',
            'bg_color' => '#fce3ed',
            'icon_color' => '#c2175c',
        ],
        [
            'key' => 'pf_pendidikan',
            'label' => 'Pendidikan',
            'bg_color' => '#f2e6fa',
            'icon_color' => '#7a1ca6',
        ],
        [
            'key' => 'pf_belanja',
            'label' => 'Belanja',
            'bg_color' => '#fce3f2',
            'icon_color' => '#850d4f',
        ],
        [
            'key' => 'pf_pengeluaran_lainnya',
            'label' => 'Pengeluaran Lainnya',
            'bg_color' => '#ffebeb',
            'icon_color' => '#b81a1a',
        ],
        [
            'key' => 'tc_top_up_dana_operasional',
            'label' => 'Top Up Dana Operasional',
            'bg_color' => '#e0f6e4',
            'icon_color' => '#228b37',
        ],
        [
            'key' => 'tc_reimbursement_kantor',
            'label' => 'Reimbursement Kantor',
            'bg_color' => '#e0f0ff',
            'icon_color' => '#0d63c0',
        ],
        [
            'key' => 'tc_refund_vendor',
            'label' => 'Refund Vendor',
            'bg_color' => '#f2e4fa',
            'icon_color' => '#853cb2',
        ],
        [
            'key' => 'tc_pemasukan_lainnya',
            'label' => 'Pemasukan Lainnya',
            'bg_color' => '#fff0df',
            'icon_color' => '#e55e02',
        ],
        [
            'key' => 'tc_transportasi_perjalanan',
            'label' => 'Transportasi & Perjalanan',
            'bg_color' => '#fee2ee',
            'icon_color' => '#dc7ba3',
        ],
        [
            'key' => 'tc_konsumsi',
            'label' => 'Konsumsi',
            'bg_color' => '#def5f3',
            'icon_color' => '#017d73',
        ],
        [
            'key' => 'tc_atk_keperluan_kantor',
            'label' => 'ATK & Keperluan Kantor',
            'bg_color' => '#e0f6e4',
            'icon_color' => '#228b37',
        ],
        [
            'key' => 'tc_komunikasi',
            'label' => 'Komunikasi',
            'bg_color' => '#e0f0ff',
            'icon_color' => '#0d63c0',
        ],
        [
            'key' => 'tc_kurir_pengiriman',
            'label' => 'Kurir / Pengiriman',
            'bg_color' => '#f2e4fa',
            'icon_color' => '#7624a8',
        ],
        [
            'key' => 'tc_entertainment',
            'label' => 'Entertainment',
            'bg_color' => '#fff0df',
            'icon_color' => '#e55e02',
        ],
        [
            'key' => 'tc_promosi_aktivasi_penjualan',
            'label' => 'Promosi & Aktivasi Penjualan',
            'bg_color' => '#fee2ee',
            'icon_color' => '#ba1458',
        ],
        [
            'key' => 'tc_biaya_meeting_klien',
            'label' => 'Biaya Meeting Klien',
            'bg_color' => '#def5f3',
            'icon_color' => '#1c8c83',
        ],
        [
            'key' => 'tc_kunjungan_lapangan',
            'label' => 'Kunjungan Lapangan',
            'bg_color' => '#e0f6e4',
            'icon_color' => '#228b37',
        ],
        [
            'key' => 'tc_recruitment',
            'label' => 'Recruitment',
            'bg_color' => '#e0f0ff',
            'icon_color' => '#0d63c0',
        ],
        [
            'key' => 'tc_employee_welfare',
            'label' => 'Employee Welfare',
            'bg_color' => '#f2e4fa',
            'icon_color' => '#7624a8',
        ],
        [
            'key' => 'tc_housekeeping_pantry',
            'label' => 'Housekeeping & Pantry',
            'bg_color' => '#fff0df',
            'icon_color' => '#e55e02',
        ],
        [
            'key' => 'tc_perbaikan_pemeliharaan',
            'label' => 'Perbaikan & Pemeliharaan',
            'bg_color' => '#fee2ee',
            'icon_color' => '#ba1458',
        ],
        [
            'key' => 'tc_operasional_kantor_lainnya',
            'label' => 'Operasional Kantor Lainnya',
            'bg_color' => '#def5f3',
            'icon_color' => '#017d73',
        ],
        [
            'key' => 'umkm_penjualan',
            'label' => 'Penjualan',
            'bg_color' => '#dcfce7',
            'icon_color' => '#16a34a',
        ],
        [
            'key' => 'umkm_komisi_bagi_hasil',
            'label' => 'Komisi & Bagi Hasil',
            'bg_color' => '#dbeafe',
            'icon_color' => '#2563eb',
        ],
        [
            'key' => 'umkm_return_investasi',
            'label' => 'Return Investasi',
            'bg_color' => '#ffedd5',
            'icon_color' => '#ea580c',
        ],
        [
            'key' => 'umkm_bunga_tabungan',
            'label' => 'Bunga Tabungan',
            'bg_color' => '#ccfbf1',
            'icon_color' => '#54baaf',
        ],
        [
            'key' => 'umkm_pendapatan_lainnya',
            'label' => 'Pendapatan Lainnya',
            'bg_color' => '#ede9fe',
            'icon_color' => '#7c3aed',
        ],
        [
            'key' => 'umkm_bahan_baku',
            'label' => 'Bahan Baku',
            'bg_color' => '#fef9c3',
            'icon_color' => '#ca8a04',
        ],
        [
            'key' => 'umkm_ongkos_kirim',
            'label' => 'Ongkos Kirim',
            'bg_color' => '#cffafe',
            'icon_color' => '#0891b2',
        ],
        [
            'key' => 'umkm_operasional_produksi',
            'label' => 'Operasional Produksi',
            'bg_color' => '#ffedd5',
            'icon_color' => '#ea580c',
        ],
        [
            'key' => 'umkm_operasional_kantor',
            'label' => 'Operasional Kantor',
            'bg_color' => '#dbeafe',
            'icon_color' => '#2563eb',
        ],
        [
            'key' => 'umkm_gaji',
            'label' => 'Gaji',
            'bg_color' => '#dcfce7',
            'icon_color' => '#16a34a',
        ],
        [
            'key' => 'umkm_bonus',
            'label' => 'Bonus',
            'bg_color' => '#fce7f3',
            'icon_color' => '#db2777',
        ],
        [
            'key' => 'umkm_iklan',
            'label' => 'Iklan',
            'bg_color' => '#fee2e2',
            'icon_color' => '#dc2626',
        ],
        [
            'key' => 'umkm_endorsement',
            'label' => 'Endorsement',
            'bg_color' => '#ede9fe',
            'icon_color' => '#7c3aed',
        ],
        [
            'key' => 'umkm_komisi_afiliasi',
            'label' => 'Komisi Afiliasi',
            'bg_color' => '#ccfbf1',
            'icon_color' => '#0d9488',
        ],
        [
            'key' => 'umkm_transportasi',
            'label' => 'Transportasi',
            'bg_color' => '#e0e7ff',
            'icon_color' => '#4338ca',
        ],
        [
            'key' => 'umkm_sewa',
            'label' => 'Sewa',
            'bg_color' => '#fee2e2',
            'icon_color' => '#dc2626',
        ],
        [
            'key' => 'umkm_administrasi',
            'label' => 'Administrasi',
            'bg_color' => '#fef9c3',
            'icon_color' => '#ca8a04',
        ],
        [
            'key' => 'umkm_pajak',
            'label' => 'Pajak',
            'bg_color' => '#dbeafe',
            'icon_color' => '#2563eb',
        ],
        [
            'key' => 'umkm_pengeluaran_lainnya',
            'label' => 'Pengeluaran Lainnya',
            'bg_color' => '#cffafe',
            'icon_color' => '#0891b2',
        ],
    ],
];